### ISSUE TITLE
熊组的文本跟码表

### ISSUE THREAD

**Issue by rcyggdra** [BSoD123456/ffta_us_cn#3]
[FFTA码表 文本.zip](https://github.com/BSoD123456/ffta_us_cn/files/13777062/FFTA.zip)
看到这个项目，我就把我之前修正导出的文本给大家作为参考吧。
蓝山魔导的样式。

**Comment by rcyggdra** [comment]
再分享点像素字体，除了丁卯其他都是开源的，https://pixeldrain.com/u/KFCxU7pB

**Comment by tringcooler** [comment]
感谢yggdra大佬！

**Comment by CnIV1** [comment]
感谢~
